src/ScoreSquid.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ScoreSquid.Web.Models;
using ScoreSquid.Web.Repositories;
using ScoreSquid.Web.ViewModels;
using AutoMapper;
using ScoreSquid.Web.Tasks;
using ScoreSquid.Web.Authentication;
using ScoreSquid.Web.ErrorHandling;

namespace ScoreSquid.Web.Controllers
{
    [HandleError]
    public class PlayerController : Controller
    {
        private IPlayerTasks playerTasks;
        private ITeamTasks teamTasks;
        private IFormsAuthentication formsAuthentication;

        public PlayerController(IPlayerTasks playerTasks, ITeamTasks teamTasks, IFormsAuthentication formsAuthentication)
        {
            this.playerTasks = playerTasks;
            this.teamTasks = teamTasks;
            this.formsAuthentication = formsAuthentication;
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var player = playerTasks.Login(model.Username, model.Password);
                
                if (player != null)
                {
                    formsAuthentication.SignIn(model.Username, model.RememberMe);

                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "MiniLeague");  
                    }
                }
                else
                {
                    ModelState.AddModelError("", "The user name or password provided is incorrect.");
                }
            }
            return View(model);
        }

        public ActionResult LogOff()
        {
            formsAuthentication.SignOut();

            return RedirectToAction("Login");
        }

        public ActionResult Register()
        {
            var teams = teamTasks.GetAll();

            var model = new RegistrationViewModel
            {
                Teams = teams
                            .ToList()
                            .Select(x => new SelectListItem
                            {
                                Text = x.Name,
                                Value = x.Id.ToString()
                            })
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Register(RegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var team = teamTasks.LoadById(model.SelectedTeamId);
                var player = Mapper.Map<Player>(model);
                player.Team = team;

                var registeredPlayer = playerTasks.Register(player);

                if (registeredPlayer != null)
                {
                    formsAuthentication.SignIn(model.Username, false);

                    return RedirectToAction("Index", "MiniLeague");  
                }
                else
                {
                    ModelState.AddModelError("", "The registration details provided are incorrect.");
                }
            }

            return View(model);
        }
    }
}

src/ScoreSquid.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        var logErrorUrl = '@Url.Action("LogJavaScriptError", "Error")';
    </script>
    <script src="@Url.Content("~/Scripts/errorhandler.js")" type="text/javascript"></script>
    @MvcMiniProfiler.MiniProfiler.RenderIncludes()
</head>

<body>
     <div id="logindisplay">
     <br />
        @Html.Partial("_LoginStatus")
    </div>

    <img src="../../Content/images/banner.JPG" alt="Score Squid" /><br />
    @RenderBody()
</body>
</html>

src/ScoreSquid.Web/Views/Shared/_LoginStatus.cshtml
@using ScoreSquid.Web.Authentication;

@if(Request.IsAuthenticated) {
    <text>Welcome <b>@(((PlayerIdentity)HttpContext.Current.User.Identity).FriendlyName)</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Player") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogIn", new { controller = "Player", returnUrl = HttpContext.Current.Request.RawUrl }) ]
}

src/ScoreSquid.Web/Views/Shared/_MINIPROFILER UPDATED Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    
    @* Make sure you've added this one line to your LAYOUT or MASTER PAGE *@
    
    @MvcMiniProfiler.MiniProfiler.RenderIncludes()
    
    
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>